"""
RAGAS-based evaluation system for measuring search quality.
Evaluates retrieval and answer generation performance using standard metrics.
"""

from typing import Dict, Any, List, Optional
import pandas as pd
from dataclasses import dataclass
from core.search_router import SearchRouter
from utils.utils import get_logger
from ragas import evaluate
from ragas.metrics import (
    answer_relevancy, context_precision, faithfulness, answer_correctness
)

logger = get_logger(__name__)

@dataclass
class RAGEvaluationMetrics:
    """Container for RAGAS evaluation metrics with scoring"""
    answer_relevancy: float     # How relevant the answer is to the question
    context_precision: float    # Precision of retrieved context
    faithfulness: float         # Factual consistency with context
    answer_correctness: float   # Overall answer quality
    overall_score: float        # Weighted average of all metrics
    
    def to_dict(self) -> Dict[str, float]:
        """Convert metrics to dictionary format"""
        return {
            'answer_relevancy': self.answer_relevancy,
            'context_precision': self.context_precision,
            'faithfulness': self.faithfulness,
            'answer_correctness': self.answer_correctness,
            'overall_score': self.overall_score
        }

class RAGEvaluator:
    """RAGAS-powered search quality evaluator with history tracking"""
    
    def __init__(self, search_router: SearchRouter = None):
        """Initialize RAGAS metrics and evaluation tracking.

        Pass in the app's SearchRouter. Building a new one here gives an
        empty index, so every search returns nothing and every score is 0.
        """
        self.search_router = search_router
        self.ragas_metrics = [
            answer_relevancy, context_precision, faithfulness, answer_correctness
        ]
        self.evaluation_history = []  # Track all evaluations
    
    # TODO: HW22 [Easy] - Count the cost before you run
    # 4 metrics x top_k samples, and each metric makes 2-3 LLM calls. At 5
    # requests/minute, how long does top_k=5 take? Show the estimate to the user
    # before running, and consider which metrics are worth it.
    def evaluate_search_quality(self, query: str, expected_skills: List[str], 
                              search_mode: str = "deep", top_k: int = 5) -> RAGEvaluationMetrics:
        """Run search and evaluate results using RAGAS quality metrics"""
        
        try:
            search_router = self.search_router or SearchRouter()
            search_result = search_router.search(query, top_k, search_mode=search_mode)
            
            if not search_result.get('results'):
                return self.create_default_metrics()
            
            candidates = search_result['results']
            return self.evaluate_with_ragas(query, candidates, expected_skills)
                
        except Exception as e:
            logger.error(f"Search quality evaluation failed: {e}")
            return self.create_default_metrics()
    
    def create_default_metrics(self) -> RAGEvaluationMetrics:
        """Return zero metrics when search fails or returns no results"""
        return RAGEvaluationMetrics(
            answer_relevancy=0.0,
            context_precision=0.0,
            faithfulness=0.0,
            answer_correctness=0.0,
            overall_score=0.0
        )
    
    def evaluate_with_ragas(self, query: str, candidates: List[Dict], 
                            expected_skills: List[str]) -> RAGEvaluationMetrics:
        """Run RAGAS evaluation on search results and calculate final metrics"""
        
        evaluation_data = self.prepare_ragas_data(query, candidates, expected_skills)
        results = evaluate(
            dataset=self.to_ragas_dataset(evaluation_data),
            metrics=self.ragas_metrics,
            llm=self.judge_llm(),                # without this, RAGAS tries OpenAI
            embeddings=self.judge_embeddings(),
            run_config=self.run_config(),
        )
        table = results.to_pandas()

        metrics = RAGEvaluationMetrics(
            answer_relevancy=self.column_mean(table, 'answer_relevancy'),
            context_precision=self.column_mean(table, 'context_precision'),
            faithfulness=self.column_mean(table, 'faithfulness'),
            answer_correctness=self.column_mean(table, 'answer_correctness'),
            overall_score=0.0
        )
        
        metrics.overall_score = self.calculate_overall_score(metrics)
        self.store_evaluation(query, metrics)
        
        return metrics
    
    # TODO: HW20 [Hard] - What is actually being evaluated?
    # Read this function carefully. The 'context' is built from metadata that is
    # empty (HW1), and the 'answer' is a sentence generated by this code, not by
    # the AI. What does faithfulness mean for a template string checked against
    # 'No metadata'?
    # Redesign it so RAGAS judges something real - for example the re-ranker's
    # assessment (response) against the candidate's resume text (context).
    # Hint: Session 8 - the question / context / answer triple.
    def prepare_ragas_data(self, query: str, candidates: List[Dict], 
                           expected_skills: List[str]) -> pd.DataFrame:
        """Convert search results to RAGAS-compatible DataFrame format"""
        
        data = []
        for candidate in candidates:
            metadata = candidate.get('metadata', {})
            
            # Create context from candidate metadata
            context_parts = []
            if 'name' in metadata:
                context_parts.append(f"Name: {metadata['name']}")
            if 'skills' in metadata:
                context_parts.append(f"Skills: {', '.join(metadata['skills'][:5])}")
            if 'experience' in metadata:
                context_parts.append(f"Experience: {metadata['experience']} years")
            
            context = " | ".join(context_parts) if context_parts else "No metadata"
            
            # Create ground truth and generated answer
            ground_truth = self.create_ground_truth(metadata.get('skills', []), expected_skills)
            generated_answer = f"{metadata.get('name', 'Candidate')} with skills in {', '.join(metadata.get('skills', [])[:3])}"
            
            data.append({
                'question': query,
                'contexts': [context],
                'ground_truth': ground_truth,
                'answer': generated_answer
            })
        
        return pd.DataFrame(data)
    
    # ---- RAGAS 0.4 plumbing ------------------------------------------------

    @staticmethod
    def to_ragas_dataset(frame: pd.DataFrame):
        """RAGAS 0.4 needs an EvaluationDataset with these field names, not a DataFrame."""
        from ragas.dataset_schema import SingleTurnSample, EvaluationDataset
        samples = []
        for _, row in frame.iterrows():
            samples.append(SingleTurnSample(
                user_input=row['question'],
                retrieved_contexts=list(row['contexts']),
                response=row['answer'],
                reference=row['ground_truth'],
            ))
        return EvaluationDataset(samples=samples)

    @staticmethod
    def judge_llm():
        from ragas.llms import LangchainLLMWrapper
        from langchain_google_genai import ChatGoogleGenerativeAI
        from utils.config import GOOGLE_API_KEY, LLM_MODEL
        from utils.utils import get_rate_limiter
        return LangchainLLMWrapper(ChatGoogleGenerativeAI(
            model=LLM_MODEL, google_api_key=GOOGLE_API_KEY,
            rate_limiter=get_rate_limiter()))   # shares the app's 5/minute budget

    @staticmethod
    def judge_embeddings():
        from ragas.embeddings import LangchainEmbeddingsWrapper
        from utils.utils import get_embeddings
        return LangchainEmbeddingsWrapper(get_embeddings())

    @staticmethod
    def run_config():
        """RAGAS defaults to 16 parallel workers and a 180s timeout. At 5
        requests per minute that means rate-limit errors, then timeouts,
        then every score comes back as NaN."""
        from ragas.run_config import RunConfig
        return RunConfig(max_workers=1, timeout=900, max_retries=10, max_wait=60)

    # TODO: HW21 [Medium] - A score of 0.00 might mean the judge failed
    # RAGAS returns NaN when the judge cannot decide (quota, timeout, bad JSON).
    # This turns NaN - and missing columns - into 0.0, which looks like a terrible
    # score. How would a user tell 'the search is bad' from 'the judge failed'?
    # Hint: Session 8 - the smoke test, and why a number is not proof it worked.
    @staticmethod
    def column_mean(table: pd.DataFrame, column: str) -> float:
        if column not in table.columns:
            return 0.0
        values = table[column].dropna()
        return float(values.mean()) if len(values) else 0.0

    def create_ground_truth(self, candidate_skills: List[str], expected_skills: List[str]) -> str:
        """Generate ground truth labels based on skill matching percentage"""
        if not expected_skills:
            return "No skills specified"
         
        matched_skills = [skill for skill in expected_skills 
                         if skill.lower() in [s.lower() for s in candidate_skills]]
        match_percentage = len(matched_skills) / len(expected_skills)
        
        if match_percentage >= 0.8:
            return f"Excellent match: {len(matched_skills)}/{len(expected_skills)} skills"
        elif match_percentage >= 0.6:
            return f"Good match: {len(matched_skills)}/{len(expected_skills)} skills"
        elif match_percentage >= 0.4:
            return f"Moderate match: {len(matched_skills)}/{len(expected_skills)} skills"
        else:
            return f"Poor match: {len(matched_skills)}/{len(expected_skills)} skills"
    
    def calculate_overall_score(self, metrics: RAGEvaluationMetrics) -> float:
        """Compute weighted average of all RAGAS metrics"""
        weights = {
            'answer_relevancy': 0.30,
            'context_precision': 0.30,
            'faithfulness': 0.20,
            'answer_correctness': 0.20
        }
        
        overall_score = (
            metrics.answer_relevancy * weights['answer_relevancy'] +
            metrics.context_precision * weights['context_precision'] +
            metrics.faithfulness * weights['faithfulness'] +
            metrics.answer_correctness * weights['answer_correctness']
        )
        
        return overall_score
    
    def store_evaluation(self, query: str, metrics: RAGEvaluationMetrics):
        """Save evaluation results to history for later analysis"""
        evaluation_record = {
            'query': query,
            'timestamp': pd.Timestamp.now(),
            'metrics': metrics.to_dict()
        }
        
        self.evaluation_history.append(evaluation_record)
    
    def get_evaluation_summary(self) -> Dict[str, Any]:
        """Get summary statistics of all evaluations performed"""
        if not self.evaluation_history:
            return {"message": "No evaluations performed yet"}
        
        # Calculate averages
        avg_metrics = {}
        for metric in ['answer_relevancy', 'context_precision', 'faithfulness', 
                      'answer_correctness', 'overall_score']:
            values = [record['metrics'][metric] for record in self.evaluation_history]
            avg_metrics[f'avg_{metric}'] = sum(values) / len(values)
        
        return {
            'total_evaluations': len(self.evaluation_history),
            'average_metrics': avg_metrics,
            'recent_evaluations': self.evaluation_history[-5:]
        }
    
    def export_evaluations(self, filename: str = "rag_evaluations.csv") -> bool:
        """Export all evaluation history to CSV file for analysis"""
        if not self.evaluation_history:
            return False
        
        try:
            export_data = []
            for i, record in enumerate(self.evaluation_history):
                row = {
                    'evaluation_id': i + 1,
                    'query': record['query'],
                    'timestamp': record['timestamp'],
                    **record['metrics']
                }
                export_data.append(row)
            
            df = pd.DataFrame(export_data)
            df.to_csv(filename, index=False)
            return True
            
        except Exception as e:
            logger.error(f"Failed to export evaluations: {e}")
            return False
